import { HighlightInit } from '@highlight-run/next/client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { env } from '~/env';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<HighlightInit
				projectId={env.HIGHLIGHT_PROJECT_ID}
				serviceName={env.HIGHLIGHT_SERVICE_NAME}
				tracingOrigins
				networkRecording={{
					enabled: true,
					recordHeadersAndBody: true,
					urlBlocklist: []
				}}
			/>

			<html lang='en'>
				<body className={inter.className}>{children}</body>
			</html>
		</>
	);
}
