name: Storybook

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - name: Install dependencies
              run: npm install -g pnpm && pnpm install
            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps
            - name: Build Storybook
              run: pnpm storybook:build --test
            - name: Serve Storybook and run tests
              run: |
                  pnpx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "pnpx http-server storybook-static --port 6006 --silent" \
                    "pnpx wait-on tcp:6006 && pnpm storybook:test"
